### ISSUE TITLE
Shared builds of ffmpeg and fprobe?

### ISSUE THREAD

**Issue by DesweR** [artenax/ffmpeg#1]
You can also do them?
This would also reduce space.
Thank you!

**Comment by artenax** [comment]
There is a shared build https://github.com/artenax/ffmpeg/releases/tag/N-113568
But it has a bug with mp3 status (looks like I should avoid unstable N versions).
There is also an old but lightweight shared libav, which can be used for some tasks.
https://github.com/artenax/libav/releases/tag/libav
